export const simulationV0Copy = {
  syntheticDryRunExplanation:
    "This view shows a synthetic dry-run using placeholder operational workload assumptions.",
  profileExplanation:
    "Typical, Busy, and Slammed change synthetic occupancy and workload pressure.",
  ratioExplanation:
    "These are planning assumptions for comparison, not staffing recommendations.",
  timelineExplanation:
    "Timeline rows show synthetic task placeholders generated by the dry-run.",
  summaryCardsExplanation:
    "These cards summarize placeholder task queue, delay, and unassigned counts.",
  occupiedBedProofExplanation:
    "Shows which synthetic bed positions were selected and which non-bed spaces were excluded.",
  artifactHashExplanation:
    "This helps verify that the same synthetic inputs produce the same dry-run artifact.",
  exportExplanation:
    "Export contains synthetic operational review data only.",
  limitationCopy: [
    "Internal synthetic dry-run only.",
    "Operational placeholders only.",
    "Manual visual review remains required.",
    "Promotion remains blocked.",
    "No optimizer.",
    "No automated assignment output.",
    "No care-quality certification.",
    "No staffing certification.",
    "No outcome prediction."
  ]
} as const;
