import "./ScenarioComparisonProof.css";

import type { ScenarioComparisonProofViewModel } from "./scenarioComparisonViewModel";

type ScenarioComparisonProofProps = {
  viewModel: ScenarioComparisonProofViewModel;
};

export function ScenarioComparisonProof({ viewModel }: ScenarioComparisonProofProps) {
  return (
    <section className="comparison-proof" aria-labelledby="comparison-proof-title">
      <div className="comparison-proof__header">
        <div>
          <p className="eyebrow">Phase 7 local proof</p>
          <h2 id="comparison-proof-title">{viewModel.label}</h2>
        </div>
        <span className="comparison-proof__badge">{viewModel.operationalOnlyLabel}</span>
      </div>

      <div className="comparison-proof__grid">
        <section className="comparison-proof__panel" aria-labelledby="baseline-title">
          <h3 id="baseline-title">Baseline Scenario</h3>
          <dl className="comparison-proof__baseline">
            <div>
              <dt>Report</dt>
              <dd>{viewModel.baseline.reportId}</dd>
            </div>
            <div>
              <dt>Scenario</dt>
              <dd>{viewModel.baseline.scenarioId}</dd>
            </div>
            <div>
              <dt>Generated Tasks</dt>
              <dd>{viewModel.baseline.totalGeneratedTasks}</dd>
            </div>
            <div>
              <dt>Warnings</dt>
              <dd>{viewModel.baseline.warningCount}</dd>
            </div>
          </dl>
        </section>

        <section className="comparison-proof__panel" aria-labelledby="comparison-summary-title">
          <h3 id="comparison-summary-title">Comparison Summary</h3>
          <dl className="comparison-proof__metrics">
            {viewModel.summaryMetrics.map((metric) => (
              <div key={metric.label}>
                <dt>{metric.label}</dt>
                <dd>{metric.value}</dd>
              </div>
            ))}
          </dl>
        </section>
      </div>

      <section className="comparison-proof__panel" aria-labelledby="comparison-rows-title">
        <h3 id="comparison-rows-title">Comparison Rows</h3>
        <div className="comparison-proof__table" role="table" aria-label="Scenario comparison rows">
          <div className="comparison-proof__table-row comparison-proof__table-row--head" role="row">
            <span role="columnheader">Scenario</span>
            <span role="columnheader">Generated</span>
            <span role="columnheader">Assigned</span>
            <span role="columnheader">Unassigned</span>
            <span role="columnheader">Minutes</span>
            <span role="columnheader">Warnings</span>
            <span role="columnheader">Busiest</span>
          </div>
          {viewModel.comparisonRows.map((row) => (
            <div className="comparison-proof__table-row" role="row" key={row.reportId}>
              <span role="cell">
                {row.scenarioId}
                {row.isBaseline ? <strong>Baseline</strong> : null}
              </span>
              <span role="cell">{row.totalGeneratedTasks}</span>
              <span role="cell">{row.assignedTaskCount}</span>
              <span role="cell">{row.unassignedTaskCount}</span>
              <span role="cell">{row.totalEstimatedTaskMinutes}</span>
              <span role="cell">{row.warningCount}</span>
              <span role="cell">
                {row.busiestMinute == null ? "None" : `${row.busiestMinute} min`}
                <small>{row.busiestMinuteTaskCount} tasks</small>
              </span>
            </div>
          ))}
        </div>
      </section>

      <div className="comparison-proof__grid comparison-proof__grid--export">
        <section className="comparison-proof__panel" aria-labelledby="export-preview-title">
          <h3 id="export-preview-title">Export Bundle Preview</h3>
          <dl className="comparison-proof__export-preview">
            <div>
              <dt>Export</dt>
              <dd>{viewModel.exportPreview.exportId}</dd>
            </div>
            <div>
              <dt>Type</dt>
              <dd>{viewModel.exportPreview.exportType}</dd>
            </div>
            <div>
              <dt>Reports</dt>
              <dd>{viewModel.exportPreview.reportCount}</dd>
            </div>
            <div>
              <dt>Comparison</dt>
              <dd>{viewModel.exportPreview.comparisonId}</dd>
            </div>
            <div>
              <dt>Generated By</dt>
              <dd>{viewModel.exportPreview.generatedBy}</dd>
            </div>
            <div>
              <dt>Source</dt>
              <dd>{viewModel.exportPreview.source}</dd>
            </div>
          </dl>
        </section>

        <section className="comparison-proof__panel" aria-labelledby="comparison-limitations-title">
          <h3 id="comparison-limitations-title">Limitations</h3>
          <ul className="comparison-proof__limitations">
            {viewModel.limitations.map((limitation) => (
              <li key={limitation}>{limitation}</li>
            ))}
          </ul>
        </section>
      </div>

      <section className="comparison-proof__panel" aria-labelledby="export-json-title">
        <h3 id="export-json-title">Export JSON Preview</h3>
        <pre className="comparison-proof__json">{viewModel.exportJsonPreview}</pre>
      </section>
    </section>
  );
}
