import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import test from "node:test";

import {
  OPERATIONAL_OUTCOME_DASHBOARD_METRIC_IDS,
  buildOperationalOutcomeDashboardProofData,
  buildPressureBandingSummary,
  resolveCanonicalMetricId,
  validateMetricAgainstRegistry,
  validateOperationalOutcomeDashboardProofData
} from "../dist/index.js";

const testDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(testDir, "../../..");

test("dashboard proof data is generated by the shared builder instead of hand-authored scenario values", () => {
  const output = buildOperationalOutcomeDashboardProofData();
  const contractSource = readFileSync(
    join(repoRoot, "packages/shared/src/outcomes/operationalOutcomeDashboardProofData.ts"),
    "utf8"
  );

  assert.deepEqual(validateOperationalOutcomeDashboardProofData(output), output);
  assert.equal(contractSource.includes("DASHBOARD_SCENARIO_DEFINITIONS"), false);
  assert.equal(contractSource.includes("nurse-walk-time"), false);
});

test("dashboard builder emits canonical registry metric ids", () => {
  const output = buildOperationalOutcomeDashboardProofData();

  for (const scenario of output.scenarios) {
    assert.deepEqual(
      scenario.operationalMetrics.map((metric) => metric.metricId),
      [...OPERATIONAL_OUTCOME_DASHBOARD_METRIC_IDS]
    );
    for (const metric of scenario.operationalMetrics) {
      assert.equal(resolveCanonicalMetricId(metric.metricId), metric.metricId);
      assert.equal(validateMetricAgainstRegistry(metric).isRegistered, true);
      assert.equal(metric.metricId.includes("-"), false);
    }
  }
});

test("dashboard builder derives pressure bands from the shared pressure banding summary", () => {
  const output = buildOperationalOutcomeDashboardProofData();

  for (const scenario of output.scenarios) {
    const banding = buildPressureBandingSummary({ metrics: scenario.operationalMetrics });
    const overallBandValue = banding.metrics.find((metric) => metric.metricId === "overall_pressure_band")?.value;
    const overallBand = banding.thresholds.find((threshold) => threshold.bandValue === overallBandValue);
    assert.equal(overallBand?.bandLabel, scenario.pressureBand);
  }
});

test("dashboard builder includes the shared ratio delta comparison", () => {
  const output = buildOperationalOutcomeDashboardProofData();

  assert.equal(output.ratioDeltaComparison.deltas.length, OPERATIONAL_OUTCOME_DASHBOARD_METRIC_IDS.length);
  assert.deepEqual(
    output.ratioDeltaComparison.deltas.map((delta) => delta.metricId).sort(),
    [...OPERATIONAL_OUTCOME_DASHBOARD_METRIC_IDS].sort()
  );
  assert.equal(output.ratioDeltaComparison.deltas.every((delta) => delta.direction === "worse"), true);
});
